recipe/meta.yaml

Closes https://github.com/PrefectHQ/prefect/issues/835

Add maintainers [ci skip]

---

.azure-pipelines/run_docker_build.sh
README.md
recipe/meta.yaml

Update recipe for 0.5.2

---

recipe/meta.yaml

Use pypi sources

---

.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
.ci_support/osx_.yaml
.ci_support/win_.yaml
README.md
azure-pipelines.yml
recipe/meta.yaml

remove typing in conda requirements for py>=3.6

---

recipe/meta.yaml

Also add myself as a recipe maintainer.

Update deps to match requirements.txt

---

recipe/meta.yaml

Add @joshmeek to maintainers

---

recipe/meta.yaml

The listed dependency requirements were out of date.

Update dependency versions

---

recipe/meta.yaml

Release 0.13.8

---

.azure-pipelines/azure-pipelines-linux.yml
.github/CODEOWNERS
README.md
recipe/meta.yaml

- Add @madkinsz as maintainer; remove outdated maintainers
Unlike the bad #103 PR this updates the meta file per https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-the-maintainer-list

Add @madkinsz as maintainer; remove outdated maintainers

---

recipe/meta.yaml

- Update minimum python version to 3.7
- Drop new from description

Updates for 1.0.0

---

.github/CODEOWNERS
README.md
recipe/meta.yaml

Update feedstock for 2.x dependencies

---

.ci_support/linux_64_.yaml
README.md
recipe/meta.yaml

Update build to use noarch for generic package

---

recipe/meta.yaml

Checklist
Closes https://github.com/PrefectHQ/prefect/issues/6198

Fix CLI entrypoint

---

recipe/meta.yaml

Oops, I didn't remember to commit it in #149

Fix build number

---

recipe/meta.yaml

- Checks that the version number is correct
- Checks that the long-form version command can be run, which pulls information about the client and database

Improve tests verifying correct installation

---

recipe/meta.yaml

Update to prefect 1.4.0

---

recipe/meta.yaml

Checklist
This PR should replace https://github.com/conda-forge/prefect-feedstock/pull/237 by adding the new `ruamel.yaml` package requirement.

Prefect v2.10.15

---

recipe/meta.yaml

Make conda dependencies match latest pip ones

---

recipe/meta.yaml

Add missing dependency constraints

---

recipe/meta.yaml

Update typer pins to align with pins set for pip upstream in prefect as of [v2.19.8](https://github.com/PrefectHQ/prefect/blob/2.19.8/requirements.txt)
Checklist

Update typer pins

---

.github/CODEOWNERS
README.md
recipe/meta.yaml

Updates maintainers to myself and @zzstoatzz

Update prefect-feedstock maintainers

---

.github/CODEOWNERS
recipe/meta.yaml

Fix dependencies in 2.20

---

recipe/meta.yaml

Remove docker-py upper version constraint

---

.scripts/build_steps.sh
azure-pipelines.yml
recipe/meta.yaml

REL: v3.0.11

---

recipe/meta.yaml

Releases 2.20.16 from a branch
